In [1]:
import numpy as np

In [2]:
# Create ndarray
a = np.array([1,2,4,5,6,7])  # from python list
a

array([1, 2, 4, 5, 6, 7])

In [3]:
type(a)

numpy.ndarray

In [4]:
a = np.array(range(1,12)) # from python list
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
a = np.linspace(0,9,10) # from linspace
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [6]:
a = np.arange(0,9,2) # from arange
a

array([0, 2, 4, 6, 8])

In [7]:
type(a)

numpy.ndarray

In [8]:
# ndarray attributes
one_dim = np.arange(12)
one_dim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
one_dim.ndim

1

In [10]:
one_dim.shape

(12,)

In [11]:
one_dim.dtype

dtype('int64')

In [12]:
one_dim.data

In [13]:
# ndarray.reshape
two_dim = one_dim.reshape(3,4)
two_dim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
two_dim.ndim

2

In [15]:
two_dim.shape

(3, 4)

In [16]:
two_dim.dtype

dtype('int64')

In [17]:
two_dim.data

In [18]:
# indexing and slicing
# at the second row and third column
two_dim[1,2]

6

In [19]:
# second row from the second to the third column
two_dim[1,1:3]

array([5, 6])

In [20]:
# including step
two_dim[:2,::2]

array([[0, 2],
       [4, 6]])

In [21]:
# Elementwise
x = np.eye(3) # Identity matrix of rank 3
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
y = np.random.rand(3,3) # numbers vary according to seed.
y

array([[0.33796407, 0.30516988, 0.8618055 ],
       [0.25592315, 0.51403989, 0.29752832],
       [0.81910741, 0.08202685, 0.56570525]])

In [23]:
x + y # Matrix addition

array([[1.33796407, 0.30516988, 0.8618055 ],
       [0.25592315, 1.51403989, 0.29752832],
       [0.81910741, 0.08202685, 1.56570525]])

In [24]:
x * y # elementwise product

array([[0.33796407, 0.        , 0.        ],
       [0.        , 0.51403989, 0.        ],
       [0.        , 0.        , 0.56570525]])

In [25]:
x @ y # Matrix product

array([[0.33796407, 0.30516988, 0.8618055 ],
       [0.25592315, 0.51403989, 0.29752832],
       [0.81910741, 0.08202685, 0.56570525]])

In [26]:
np.transpose(y) # transpose y

array([[0.33796407, 0.25592315, 0.81910741],
       [0.30516988, 0.51403989, 0.08202685],
       [0.8618055 , 0.29752832, 0.56570525]])

In [27]:
# Useful Methods
z = np.random.rand(3,5)
z

array([[0.36488258, 0.42832011, 0.52163065, 0.36104355, 0.2220257 ],
       [0.5317947 , 0.11829943, 0.38896734, 0.85709538, 0.21287809],
       [0.56375104, 0.17774231, 0.14224724, 0.70974331, 0.50629906]])

In [28]:
z.sum()

6.106720484553554

In [29]:
z.min(axis = 0)

array([0.36488258, 0.11829943, 0.14224724, 0.36104355, 0.21287809])

In [30]:
z.min(axis = 1)

array([0.2220257 , 0.11829943, 0.14224724])

In [31]:
z.mean()

0.40711469897023694

In [32]:
z.mean(axis = 0)

array([0.48680944, 0.24145395, 0.35094841, 0.64262741, 0.31373428])

In [33]:
z.mean(axis = 1)

array([0.37958052, 0.42180699, 0.41995659])