In [1]:
import numpy as np

In [2]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
arr[:4]

array([0, 1, 2, 3])

In [4]:
alist = list(range(12))
alist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [5]:
alist[:4]

[0, 1, 2, 3]

In [6]:
a = np.array([1,2,'b','c'])
a

array(['1', '2', 'b', 'c'], dtype='<U21')

In [7]:
a.dtype.name

'str672'

In [8]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [10]:
np.empty( (2,3) )

array([[4.6392925e-310, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [11]:
np.arange(0,2,0.5)

array([0. , 0.5, 1. , 1.5])

In [12]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
arr_3d =np.array([ [[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]],

                   [[13, 14, 15, 16],
                    [17, 18, 19, 20],
                    [21, 22, 23, 24]]], dtype=np.int16)
arr_3d.shape

(2, 3, 4)

In [14]:
arr_3d[0,1:3,2:]

array([[ 7,  8],
       [11, 12]], dtype=int16)

In [15]:
arr_3d[:2,:,1:3]

array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]], dtype=int16)

In [16]:
arr_3d[...,::2]

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11]],

       [[13, 15],
        [17, 19],
        [21, 23]]], dtype=int16)

In [17]:
arr_3d[:,:,::2]

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11]],

       [[13, 15],
        [17, 19],
        [21, 23]]], dtype=int16)

In [18]:
arr_3d[:,1]

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]], dtype=int16)

In [19]:
arr_3d[:,1,...]

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]], dtype=int16)

In [20]:
for blocks in arr_3d:
    for row in blocks:
        print(row)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]
[17 18 19 20]
[21 22 23 24]


In [21]:
for items in arr_3d.flat:
    print(items,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 

In [22]:
boxes = np.arange(1,121)
boxes

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120])

In [23]:
boxes.reshape(3,40)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
         67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
        107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
        120]])

In [24]:
boxes.reshape(3,2,-1)

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
          13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
          33,  34,  35,  36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
          53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
          73,  74,  75,  76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
          93,  94,  95,  96,  97,  98,  99, 100],
        [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
         113, 114, 115, 116, 117, 118, 119, 120]]])

In [25]:
a = np.arange(4)
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [26]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 ])

In [27]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [28]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [29]:
x = np.eye(3) #Identity matrix of rank 3
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
y = np.arange(9).reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
x + y

array([[1., 1., 2.],
       [3., 5., 5.],
       [6., 7., 9.]])

In [32]:
x * y

array([[0., 0., 0.],
       [0., 4., 0.],
       [0., 0., 8.]])

In [33]:
x @ y # matrix multiplication

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [34]:
y - x

array([[-1.,  1.,  2.],
       [ 3.,  3.,  5.],
       [ 6.,  7.,  7.]])

In [35]:
A = np.array([1]*4).reshape((2,2))
A

array([[1, 1],
       [1, 1]])

In [36]:
B = np.array([2]*4).reshape((2,2))
B

array([[2, 2],
       [2, 2]])

In [37]:
np.vstack((A,B))

array([[1, 1],
       [1, 1],
       [2, 2],
       [2, 2]])

In [38]:
np.hstack((A,B))

array([[1, 1, 2, 2],
       [1, 1, 2, 2]])

In [39]:
np.column_stack((A,B))

array([[1, 1, 2, 2],
       [1, 1, 2, 2]])

In [40]:
np.row_stack((A,B))

array([[1, 1],
       [1, 1],
       [2, 2],
       [2, 2]])